version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - frontback-network

networks:
  frontback-network:
    driver: bridge