services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - frontback-network
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - frontback-network
    restart: unless-stopped

networks:
  frontback-network:
    driver: bridge