services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://ec2-3-34-245-132.ap-northeast-2.compute.amazonaws.com
      - GOOGLE_REDIRECT_URI=http://ec2-3-34-245-132.ap-northeast-2.compute.amazonaws.com/auth/google/callback
    env_file:
      - ./backend/.env
    volumes:
      - ./uploads:/app/uploads
      - ./result:/app/result
    networks:
      - frontback-network
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://ec2-3-34-245-132.ap-northeast-2.compute.amazonaws.com
      - REACT_APP_GOOGLE_REDIRECT_URI=http://ec2-3-34-245-132.ap-northeast-2.compute.amazonaws.com/auth/google/callback
    env_file:
      - ./frontend/.env
    networks:
      - frontback-network
    restart: unless-stopped

networks:
  frontback-network:
    driver: bridge